### ISSUE TITLE
Change burnInfo data structure

### ISSUE THREAD

**Issue by cuongquangnam** [BirthdayResearch/StateRelayer#30]
The information should be sourced from [here](https://ocean.defichain.com/v0/mainnet/stats/burn), not [here](https://ocean.defichain.com/v0/mainnet/stats)

**Comment by Abhishekkochar** [comment]
Can you explain why is that? Key fields mention at current implementation is same from both of them.

**Comment by Abhishekkochar** [comment]
`    struct BurnedInformation{
        uint256 fee;
        uint256 auction;
        uint256 payback;
        uint256 emission;
        uint256 total;
        uint40 decimals;
    }`

These fields have same input from both.

**Comment by cuongquangnam** [comment]
But it seems DeFiChain team wants all, as communicated with Shoham
